package entities

const RESOURCE_USER = "user"
const RESOURCE_ORGANIZATION = "organization"
const RESOURCE_PIPELINE = "pipeline"
const RESOURCE_METRICS = "metrics"
const RESOURCE_TASK = "task"
const RESOURCE_STAT = "stat"
const RESOURCE_INTEGRATION = "integration"
const RESOURCE_INVITATION = "invitation"
const RESOURCE_FOLDER = "folder"
const RESOURCE_ENVVARIABLE = "envvariable"
const RESOURCE_OAUTH_CLIENT = "oauth_client"
const RESOURCE_SUBSCRIPTION_PLAN = "subscription_plan"
const RESOURCE_SUBSCRIPTION = "subscription"
const RESOURCE_CHECKOUT_SESSION = "checkout_session"
const RESOURCE_API_CALL = "api_call"
