export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const ORGANIZATION_UPDATE_SUCCESS = "ORGANIZATION_UPDATE_SUCCESS";
export const ORGANIZATION_UPDATE_FAIL = "ORGANIZATION_UPDATE_FAIL";

export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS";
export const USER_UPDATE_FAIL = "USER_UPDATE_FAIL";
export const PASSWORD_UPDATE_SUCCESS = "PASSWORD_UPDATE_SUCCESS";
export const PASSWORD_UPDATE_FAIL = "PASSWORD_UPDATE_FAIL";

export const INTEGRATION_UPDATE_SUCCESS = "INTEGRATION_UPDATE_SUCCESS";
export const INTEGRATION_UPDATE_FAIL = "INTEGRATION_UPDATE_FAIL";
export const INTEGRATION_CREATE_SUCCESS = "INTEGRATION_CREATE_SUCCESS";
export const INTEGRATION_CREATE_FAIL = "INTEGRATION_CREATE_FAIL";
export const INTEGRATION_TEST_SUCCESS = "INTEGRATION_TEST_SUCCESS";
export const INTEGRATION_TEST_FAIL = "INTEGRATION_TEST_FAIL";

export const PIPELINE_UPDATE_SUCCESS = "PIPELINE_UPDATE_SUCCESS";
export const PIPELINE_UPDATE_FAIL = "PIPELINE_UPDATE_FAIL";
export const PIPELINE_CREATE_SUCCESS = "PIPELINE_CREATE_SUCCESS";
export const PIPELINE_CREATE_FAIL = "PIPELINE_CREATE_FAIL";

export const TASK_UPDATE_SUCCESS = "TASK_UPDATE_SUCCESS";
export const TASK_UPDATE_FAIL = "TASK_UPDATE_FAIL";
export const TASK_CREATE_SUCCESS = "TASK_CREATE_SUCCESS";
export const TASK_CREATE_FAIL = "TASK_CREATE_FAIL";
export const TASK_DELETE_SUCCESS = "TASK_DELETE_SUCCESS";
export const TASK_DELETE_FAIL = "TASK_DELETE_FAIL";

export const FOLDER_UPDATE_SUCCESS = "FOLDER_UPDATE_SUCCESS";
export const FOLDER_UPDATE_FAIL = "FOLDER_UPDATE_FAIL";
export const FOLDER_CREATE_SUCCESS = "FOLDER_CREATE_SUCCESS";
export const FOLDER_CREATE_FAIL = "FOLDER_CREATE_FAIL";
export const FOLDER_DELETE_SUCCESS = "FOLDER_DELETE_SUCCESS";
export const FOLDER_DELETE_FAIL = "FOLDER_DELETE_FAIL";

export const ENV_VARIABLE_UPDATE_SUCCESS = "ENV_VARIABLE_UPDATE_SUCCESS";
export const ENV_VARIABLE_UPDATE_FAIL = "ENV_VARIABLE_UPDATE_FAIL";
export const ENV_VARIABLE_CREATE_SUCCESS = "ENV_VARIABLE_CREATE_SUCCESS";
export const ENV_VARIABLE_CREATE_FAIL = "ENV_VARIABLE_CREATE_FAIL";
export const ENV_VARIABLE_DELETE_SUCCESS = "ENV_VARIABLE_DELETE_SUCCESS";
export const ENV_VARIABLE_DELETE_FAIL = "ENV_VARIABLE_DELETE_FAIL";

export const TASK_TRIGGER_UPDATE_SUCCESS = "TASK_TRIGGER_UPDATE_SUCCESS";
export const TASK_TRIGGER_UPDATE_FAIL = "TASK_TRIGGER_UPDATE_FAIL";
export const TASK_TRIGGER_CREATE_SUCCESS = "TASK_TRIGGER_CREATE_SUCCESS";
export const TASK_TRIGGER_CREATE_FAIL = "TASK_TRIGGER_CREATE_FAIL";
export const TASK_TRIGGER_DELETE_SUCCESS = "TASK_TRIGGER_DELETE_SUCCESS";
export const TASK_TRIGGER_DELETE_FAIL = "TASK_TRIGGER_DELETE_FAIL";

export const SALESFORCE_AUTHORIZATION_UPDATE_SUCCESS = "SALESFORCE_AUTHORIZATION_UPDATE_SUCCESS";
export const SALESFORCE_AUTHORIZATION_UPDATE_FAIL = "SALESFORCE_AUTHORIZATION_UPDATE_FAIL";

export const SLACK_AUTHORIZATION_UPDATE_SUCCESS = "SLACK_AUTHORIZATION_UPDATE_SUCCESS";
export const SLACK_AUTHORIZATION_UPDATE_FAIL = "SLACK_AUTHORIZATION_UPDATE_FAIL";

export const JIRA_AUTHORIZATION_UPDATE_SUCCESS = "JIRA_AUTHORIZATION_UPDATE_SUCCESS";
export const JIRA_AUTHORIZATION_UPDATE_FAIL = "JIRA_AUTHORIZATION_UPDATE_FAIL";

export const OAUTH_CLIENT_CREATE_FAIL = "OAUTH_CLIENT_CREATE_FAIL";
export const OAUTH_CLIENT_CREATE_SUCCESS = "OAUTH_CLIENT_CREATE_SUCCESS";

export const HUBSPOT_AUTHORIZATION_UPDATE_SUCCESS = "HUBSPOT_AUTHORIZATION_UPDATE_SUCCESS";
export const HUBSPOT_AUTHORIZATION_UPDATE_FAIL = "HUBSPOT_AUTHORIZATION_UPDATE_FAIL";
