services: 
  ylem_ui_production:
    build: 
      context: .
      args:
        REACT_APP_ENVIRONMENT: prod
        #REACT_APP_BACKEND_URL: //api.ylem.co
      dockerfile: Dockerfile
    container_name: ylem_ui_production
    networks:
      - ylem_network
    ports:
      - "7440:7440"        
    volumes: 
      - ./:/frontend
      - /frontend/node_modules
    stdin_open: true

networks:
  default:
    name: ylem_network
    external: true
